buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.0'
        // Chaquopy: يدمج مفسّر بايثون داخل تطبيق أندرويد
        classpath 'com.chaquo.python:gradle:15.0.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
